### PR TITLE
Revert "Do not include external modules in bundle"

### PR DESCRIPTION
**Pull request by patriciagarcia**
Reverts fielded/angular-nav-data#18

See #20

### CODE REVIEW

**Comment by tlvince** [comment]
Does that fix "Cannot call a class as a function"?

**Comment by patriciagarcia** [comment]
Ooops, I was planning to merge this before the other PR, yep, it fixes it, although we have to find a better way to fix it, so leave the other issue for now

**Comment by tlvince** [comment]
Oh OK cool. np, it won't get included in the state dash until we unpin anyway.

**Comment by tlvince** [comment]
LGTM.

**Pull request merged**
